---
format:
  html:
    title: ""
    toc: true
  pdf:
    title: CV
    pdf-engine: weasyprint
css: cv.css
format-links: [pdf]
---

::: {.print-only .contact-block}
[Tyler J. Law, MD, MSc]{.author} <br>
University of California, San Francisco, San Francisco, CA ▪ [tyler.law@ucsf.edu](tyler.law@ucsf.edu)
---
:::

# [TYLER J. LAW, MD, MSc]{.no-print}
[University of California, San Francisco, San Francisco, CA ▪ [tyler.law@ucsf.edu](tyler.law@ucsf.edu)]{.contact-block .no-print}

## EDUCATION

**Anesthesia Critical Care Medicine Fellowship** [2021]{.cvdate}<br> 
University of California, San Francisco, Department of Anesthesia and Perioperative Care

**Global Health Equity Fellowship** [2018]{.cvdate}<br>
University of California, San Francisco, Department of Anesthesia and Perioperative Care

**Fellow of the Royal College of Physicians and Surgeons (Anesthesiology)** [2017]{.cvdate}<br>
University of Toronto, Toronto, Canada

**Master of Science, Health Policy, Planning and Financing** [2015]{.cvdate}<br>
London School of Economics, London, UK

**Doctor of Medicine** [2012]{.cvdate}<br>
Queen’s University, Kingston, Canada

**Bachelor of Health Sciences** [2008]{.cvdate}<br>
McMaster University, Hamilton, Canada

## PRINCIPAL APPOINTMENTS

**Assistant Professor** [July, 2018 – present]{.cvdate}<br>
University of California, San Francisco, Department of Anesthesiology & Perioperative Care

**Clinical Instructor (Anesthesiology)** [July, 2017 – June, 2018]{.cvdate}<br>
University of California, San Francisco

**Attending Physician (Anesthesiology)** [July, 2017 – June, 2018]{.cvdate}<br>
Zuckerberg San Francisco General Hospital

## OTHER POSITIONS

**Chair, Code Blue Committee** [2022 - current]{.cvdate}<br>
Zuckerberg San Francisco General Hospital

**Associate Director of Research, Center for Health Equity in Surgery and Anesthesia** [2022 - current]{.cvdate}<br>
University of California, San Francisco

**Faculty Recruitment Committee, ZSFG** [2022 - current]{.cvdate}<br>

**Research Assistant, LSE Health** [January, 2015 – September, 2015]{.cvdate}<br>
London School of Economics, London, UK

**Visiting Research Student, Outcomes After Critical Illness and Surgery** [May – August, 2010]{.cvdate}<br>
Johns Hopkins University, Baltimore, USA

**Research Fellow, McMaster University Health Forum** [2009]{.cvdate}<br>
McMaster University, Hamilton, ON

**Intern, National Institute for Health Research, Department of Health** [August, 2008]{.cvdate}<br>
London, United Kingdom

**Intern, Alliance for Health Policy and Systems Research** [April – July, 2008]{.cvdate}<br>
World Health Organization, Geneva, Switzerland

**Research Assistant, Program in Policy Decision-Making** [2007 – 2008]{.cvdate}<br>
McMaster University, Hamilton, ON

## RESEARCH

### Peer-Reviewed Publications
1. Miclau, Theodore A., Daniel J. Bennett, Laura Lang, Megha Parekh, and **Tyler J. Law**. 2024. “Rideshare-Based Transportation Services for Surgical Patients in an Urban Setting: A Descriptive Analysis of a Quality Initiative Program.” *Journal of Transport & Health* 36 (May): 101813.
1. **Law, Tyler J.**, Michael S. Lipnick, Wayne Morriss, Adrian W. Gelb, Jannicke Mellin-Olsen, Daniela Filipescu, Jackie Rowles, et al. 2024. “The Global Anesthesia Workforce Survey: Updates and Trends in the Anesthesia Workforce.” *Anesthesia & Analgesia*, March, 10.1213/ANE.0000000000006836.
1. Leeb, Gregory, Isabella Auchus, **Tyler Law**, Philip Bickler, John Feiner, Shamsudini Hashi, Ellis Monk, et al. 2024. “The Performance of 11 Fingertip Pulse Oximeters during Hypoxemia in Healthy Human Participants with Varied, Quantified Skin Pigment.” *EBioMedicine* 102 (March): 105051.
1. Petrucci, Beatriz, Samuel Okerosi, Rolvix H. Patterson, Sara B. Hobday, Valerie Salano, Christopher J. Waterworth, **Tyler J. Law**, Robert M. Brody, et al. 2023. “The Global Otolaryngology-Head and Neck Surgery Workforce.” *JAMA Otolaryngology-- Head & Neck Surgery*, August. https://doi.org/10.1001/jamaoto.2023.2339.
1. Lilaonitkul, M., A. Zacharia, **T. J. Law**, N. Yusuf, P. Saria, and J. Moore. 2023. “Evaluation of Practice Change Following SAFE Obstetric Courses in Tanzania: A Prospective Cohort Study.” *Anaesthesia*, July. https://doi.org/10.1111/anae.16091.
1. Fong, Nicholas, Erica Langnas, **Tyler Law**, Mallika Reddy, Michael Lipnick, and Romain Pirracchio. 2023. “Availability of Information Needed to Evaluate Algorithmic Fairness - A Systematic Review of Publicly Accessible Critical Care Databases.” *Anaesthesia, Critical Care & Pain Medicine*, May, 101248.
1. Percy, Samuel, Saad Sahi, Emmanuel Bua, Sriram Shamasunder, Michael Lipnick, and **Tyler Law**. 2023. “Living the Work: The HEAL Initiative as a Model for Perioperative Health Workforce Transformation and Health Equity Work.” *Canadian Journal of Anaesthesia = Journal Canadien D’anesthesie*, May, 1–4.
1. **Law, Tyler J.**, Derek Stephens, and James G. Wright. 2022. “Surgical Wait Times and Socioeconomic Status in a Public Healthcare System: A Retrospective Analysis.” *BMC Health Services Research* 22 (1): 579.
1. Henson, Laurence Cyril O., Courtney R. Lyles, Christy J. Khouderchah, and **Tyler J. Law**. 2021. “Impact of Gentrification on Asthma Visits to the Emergency Department.” *SN Social Sciences* 2 (1): 3.
1. **Law, Tyler J.**, Shivani Subhedar, Fred Bulamba, Nathan N. O’Hara, Mary T. Nabukenya, Cornelius Sendagire, Adam Hewitt-Smith, Michael S. Lipnick, and Janat Tumukunde. 2021. “Factors Affecting Job Choice among Physician Anesthesia Providers in Uganda: A Survey of Income Composition, Discrete Choice Experiment, and Implications for the Decision to Work Rurally.” *Human Resources for Health* 19 (1): 93.
1. Sund, G. C., M. S. Lipnick, **T. J. Law**, E. A. Wollner, and G. E. Rwibuka. 2021. “Anaesthesia Facility Evaluation: A Whatsapp Survey of Hospitals in Burundi.” *South African Journal of Anaesthesia and Analgesia* 27 (2). http://www.sajaa.co.za/index.php/sajaa/article/view/2456.
1. Wollner, Elliot, Maziar M. Nourian, William Booth, Sophia Conover, **Tyler Law**, Maytinee Lilaonitkul, Adrian W. Gelb, and Michael S. Lipnick. 2020. “Impact of Capnography on Patient Safety in High- and Low-Income Settings: A Scoping Review.” *British Journal of Anaesthesia* 125 (1): e88–103.
1. Wollner, Elliot, **Tyler Law**, Kristina Sullivan, and Michael S. Lipnick. 2020. “Why Every Anesthesia Trainee Should Receive Global Health Equity Education.” *Canadian Journal of Anaesthesia = Journal Canadien D’anesthesie* 67 (8): 924–35.
1. Zha, Yuanting, Paul Truché, Erick Izquierdo, Kathrin Zimmerman, Sandra de Izquierdo, Michael S. Lipnick, **Tyler J. Law**, Adrian W. Gelb, and Faye M. Evans. 2020. “Assessment of Anesthesia Capacity in Public Surgical Hospitals in Guatemala.” *Anesthesia and Analgesia*, November. https://doi.org/10.1213/ANE.0000000000005297.
1. **Law, Tyler J.**, Michael Lipnick, Muralidhar Joshi, Girija P. Rath, and Adrian W. Gelb. 2019. “The Path to Safe and Accessible Anaesthesia Care.” *Indian Journal of Anaesthesia* 63 (12): 965–71.
1. **Law, Tyler J.**, Fred Bulamba, John Paul Ochieng, Hilary Edgcombe, Victoria Thwaites, Adam Hewitt-Smith, Eugene Zoumenou, et al. 2019. “Anesthesia Provider Training and Practice Models: A Survey of Africa.” *Anesthesia & Analgesia* 129 (3): 839.
1. Bulamba, Fred, Cornelius Sendagire, Andrew Kintu, Adam Hewitt-Smith, Fred Musana, Maytinee Lilaonitkul, Emmanuel T. Ayebale, **Tyler Law**, et al. 2018. “Feasibility of Simulation-Based Medical Education in a Low-Income Country: Challenges and Solutions From a 3-Year Pilot Program in Uganda.” *Simulation in Healthcare: Journal of the Society for Simulation in Healthcare*. https://europepmc.org/abstract/med/30601468.
1. Salcher M, Naci H, **Law TJ**, Kuehne T, Schubert S, Kelm M, et al. Balloon Dilatation and Stenting for Aortic Coarctation: A Systematic Review and Meta-Analysis. *Circ Cardiovasc Interv*. 2016;9(6).
1. **Law TJ**, Leistikow NA, Hoofring L, Krumm SK, Neufeld KJ, Needham DM. A survey of nurses' perceptions of the intensive care delirium screening checklist. *Dynamics*. 2012 Winter;23(4):18-24.
1. **Law TJ**, Lavis JN, Hamandi A, Cheung A, El-Jardali F, KT Platform Evaluation Team. Climate for evidence-informed health systems: A profile of systematic review production in 41 low- and middle-income countries, 1996-2008. *J Health Serv Res Policy*. 2012 Jan;17(1):4-10.
1. Desai SV, **Law TJ**, Needham DM. Long-term Complications of Critical Care. *Crit Care Med*. 2011 Feb;39(2):371-9.
1. Ranson K, **Law TJ**, Bennett S. Establishing health systems financing research priorities in developing countries using a participatory methodology. *Soc Sci Med* 2010 Jun;70(12):1933-42.

### Other Publications
1. Rose, John, and **Law, Tyler**. 2023. “The Madagascar Experience: A Step Forward in Population-Level Evidence to Guide National Surgical Obstetrics and Anesthesia Planning.” *Canadian Journal of Anaesthesia = Journal Canadien D’anesthesie.*
1. **Law, Tyler J.**, John Rose, and Adrian W. Gelb. 2022. “Initiatives to Support Rural Access to Anesthesia.” *Canadian Journal of Anaesthesia*.
1. Chapter 2: Anesthesia in the Global Context (Canada section). **Law, TJ**. In: *Miller's Anesthesia, 9th edition*. Ed: Gropper, M. Miller, R. 2019.
1. Avoidable Surgeries: Description and Identification of a Novel Health Systems Indicator. **Law, TJ**. London School of Economics. 2015. (Master’s Thesis).
1. Desai SV, **Law TJ**, Bienvenu OJ, Needham DM. Response to Psychiatric long-term complications of intensive care unit survivors. *Crit Care Med*. 2012.
1. AFMC Primer on Population Health. Reviewer for Chapter 12: The Organisation of Health Services in Canada, and Chapter 14: Decision-making: Policies and Ethics in Health Care and Public Health. http://phprimer.afmc.ca/inner/primer_contents. 2011.

### Current and Completed Research Funding
### Ongoing Research Support

::: {.flex-container}
[**FDA CERSI - Grant#70**]{.flex-left} [*Bickler, Hendrickson, Lipnick (PIs)*]{.flex-center} [09/2023 - 08/2024]{.flex-right}  
:::
**Funding amount:** $23,431 for FTE  
“Prospective Clinical Study of Pulse Oximeter Errors in Hospitalized Patients.”  
The “Equiox” clinical study of pulse oximeters and skin tone in critically ill patients  
**Role**: Key personnel (data analytics – dashboard reporting metrics, descriptive analysis)

::: {.flex-container}
[**UNITAID/PATH**]{.flex-left} [*Lipnick (PI)*]{.flex-center} [03/2023 - 06/2024]{.flex-right}  
:::
**Funding amount:** $50,534 for FTE  
Open Oximetry: Create and manage an open access oximeter performance data repository for pulse oximeters, including raw signal data, perfusion and skin pigment data, populated by our lab and other teams using standardized data collection methods established by the Open Oximetry project.  
**Role**: Key personnel (data analytics and project support)

#### Completed Research Support

::: {.flex-container}
[**USAID Assessments**]{.flex-left} [*Lipnick (PI)*]{.flex-center} [10/2022 - 03/2024]{.flex-right}
:::
**Funding amount:** $30,064 for FTE  
Assessing USAID funded implementation of oxygen infrastructure (LOX, PSA) support projects, and Test-to-Treat uptake implementation.  
**Role**: Key personnel (planning and implementing data capture processes, survey implementation and analysis)

::: {.flex-container}
**CHESA Seed Award** *Law (PI)* 08/2022 - 08/2023
:::
**Funding amount:** $2000  
Understanding anesthesia graduates’ practice environments and reach to underserved communities

::: {.flex-container}
[**USAID COVID-19 (Global Goods)**]{.flex-left} [*Lipnick (PI)*]{.flex-center} [12/2021 - 11/2023]{.flex-right}  
:::
**Funding amount:** $101,570 for FTE  
Working with USAID and USAID’s NGO Implementing Partners to create global goods for supporting country level teams with COVID19 clinical care and respiratory care.  
**Role**: Key personnel (supporting creation of COVID19 related decision aids, educational tools, webinars etc.)

::: {.flex-container}
[**USAID COVID-19 (O2)**]{.flex-left} [*Lipnick (PI)*]{.flex-center} [05/2020 - 12/2021]{.flex-right}  
:::
**Funding amount:** $45,243 for FTE  
Continuing the work from the previous award to support technical teams in the COVID response and create clinical case management tools for global consumption.  
**Role**: Key personnel (supporting creation of COVID19 related decision aids, educational tools, webinars etc.)

# PRESENTATIONS

## INTERNATIONAL PRESENTATIONS

1. **The Human Resource Factors in Anesthesia Safety.** *Fighting Fatigue Together: Prioritizing Workforce Well-being for Enhanced Patient Safety (European Patient Safety Foundation webinar), June 12, 2024*
1. **Mapping the Global Anesthesia Workforce.** *European Society of Anesthesia and Intensive Care Medicine (ESAIC) Conference, Munich, Germany, 2024*
1. **Challenges in Workforce Data Collection.** *Utstein Business Meeting, World Congress of Anesthesia Conference, Singapore, 2024.*
1. **The WFSA Workforce Survey.** *International Anesthesia Research Society. Denver, CO. 2023.*
1. **The WFSA Workforce Survey: the final data.** *American Society of Anesthesiologists 2022 Conference, New Orleans, USA, October 24, 2022*
1. **Counting and Retaining the Anesthesia Workforce.** *All Africa Anesthesia Conference. Kigali, Rwanda. September 10, 2022.*
1. **Anesthesia, Critical Care, and UHC.** *13th International Society for Priorities in Health Conference. Bergen, Norway (virtual). April 28, 2022.*
1. **Challenges of Assessing Oxygen Use, and the Clinical Care Tools Developed during the Pandemic.** *22nd ASEAN Congress of Anesthesiologists, Hanoi, Vietnam (virtual). March 19, 2022.*
1. **Surgical wait times and socioeconomic status in a publicly funded health care system.** **Tyler J. Law**, Derek Stephens, James G. Wright. *American Society of Anesthesiologists 2018 Conference, San Francisco, California*
1. **National Workforce Planning - A model.** *Association of Anesthesiologists of Uganda Conference, Kampala, Uganda, 2018*
1. **Student superheroes in interprofessionalism.** *National Health Science Students’ Association Conference, Toronto, 2011*
1. **Interprofessionalism: Who, when?** *Virginia Tech Carilion School of Medicine, Roanoke, Virginia, 2010*

## Abstracts

<!-- rideshare abstract miclau -->

**Investigating Intrinsic Bias in Publically Available Critical Care Datasets for Machine Learning.** Fong, Nicholas, Erica Langnas, **Tyler Law**, Mallika Reddy, Michael Lipnick, and Romain Pirracchio. *International Anesthesia Research Society, Denver, CO, 2023*

**Heterogeneity of non-physician anesthesia provider training and practice models: a survey of Africa.** **Tyler J. Law**, MD, MSc*, Fred Bulamba MBChB*, J.P. Ochieng, MBChB4, Hilary Edgecombe, MBBS2, Victoria Thwaites, MBBS3, A. Hewitt Smith, MBBS, Eugene Zoumenou, Maytinee Lilaonitkul, MBBS, Adrian Gelb, MD, Redeit Shimeles, Paulin Banguti, Dylan Bould, Pascal Rod, Jackie Rowles, Francisco Lobo, Michael S. Lipnick, MD The Global Anesthesia Workforce Study Group
*Stanford-UCSF Anesthesia Research Retreat, San Francisco, 2018*
*UCSF Research Day, San Francisco, 2018*
*American Society of Anesthesiologists, San Francisco, 2018*

**Heterogeneity in anesthesia practice models worldwide: a descriptive review of 11 high-income countries.** Aya Abounasr, Michael S. Lipnick, Adrian Gelb, Elise A. Delagnes, Maytinee Lilaonitkul, **Tyler Law**.
*American Society of Anesthesiologists, San Francisco, 2018*
*UCSF Research Day, San Francisco, 2018*

**Surgical wait times and socioeconomic status in a publicly funded health care system.** **Tyler J. Law**, Derek Stephens, James G. Wright. 
*American Society of Anesthesiologists, San Francisco, 2018*

**Development Of A Facility-based, Anesthesia Capacity Assessment Tool For Resource-constrained Settings.** Elise Delagnes, M.D, M.A, Shirley Zhao, B.S., Fred Bulamba, M.D., **Tyler J. Law**, M.D., Adrian W. Gelb, M.D., Stephen Ttendo, M.D., Adam Hewitt-Smith, M.D., Joseph Kiwanuka, M.D., Faye M. Evans, M.D., Michael S. Lipnick, M.D.
*American Society of Anesthesiologists, San Francisco, 2018*
*UCSF Research Day, San Francisco, 2018*
*College of Surgeons of East, Central, and South Africa, Kigali, Rwanda, 2018*


# AWARDS AND SCHOLARSHIPS

**Early Career Global Health Scientist Award, Institute for Global Health Sciences, UCSF**[Jan, 2024]{.cvdate}<br>
[https://globalhealthsciences.ucsf.edu/early-career-global-health-scientist-awards-highlight-projects-that-reimagine-global-health/](https://globalhealthsciences.ucsf.edu/early-career-global-health-scientist-awards-highlight-projects-that-reimagine-global-health/)

**Academy of Educators Excellence in Teaching Award, UCSF School of Medicine** [Sept, 2023*]{.cvdate}<br>

<!-- **Dr. And Mrs. Sydney P. Schiff Award, Queen’s University** [*May, 2012*]{.cvdate}<br>
*For highest mark in medical school surgery rotation*

**T. Russel Wilkins Memorial Travel Scholarship, McMaster University – $4600** [*May, 2008*]{.cvdate}<br>
*For a student demonstrating lively interest in humanities and the human/social implications of scientific developments. To enable the winners to spend the summer in travel and study outside of Canada.*

**Bachelor of Health Science Research Scholarship, McMaster University – $2000** [*May, 2007*]{.cvdate}<br>
*To support research on evaluating 28 international WHO sponsored Knowledge-Translation networks* -->

# STUDENTS MENTORED

1. **Aya Abounasr (2017-2018):** Mentored 4th year medical student project, paper submitted for publication. 
1. **Shivani Subhedar (2018-2019):** Mentored UCSF Global Health Master’s student for capstone project.
2. **Amy Chen (2018-2019):** UCSF anesthesiology resident examining factors contributing to positive medical student clerkship in anesthesia.
1. **Laurence Henson (2019-2020):** Supervisor for UCSF Master’s in Epidemiology student, project on health outcomes and gentrification.
1. **Sofia Lochner (2021-2022):** Supervisor for UCSF Global Health Master’s project, examining National Surgical Obstetric and Anesthesia Plans.
1. **Lauren Locke (2022-2023):** Supervisor for residency Global Health track project on factors associated with anesthesia residents working with rural and underserved populations. 

<!-- # TEACHING

**STARS lecture “Health Systems”** [*July 2017 – July 2018*]{.cvdate}<br>
*Monthly lecture to UCSF anesthesia residents*

**Anesthesia Education Day “Global Health”** [*2017*]{.cvdate}<br>
*3 part lecture series for UCSF anesthesia residents, held yearly*	

**Facilitator, Anesthesia Interest Group skills night** [*April 6, 2016*]{.cvdate}<br>
*University of Toronto medical students* [*January 20, 2016*]{.cvdate}

**Facilitator, Airway day** [*March 2, 2016*]{.cvdate}<br>
*University of Toronto medical students*

**Assessor, Medical Student Transition to Residency Course** [*February, 2016*]{.cvdate}<br>
*University of Toronto, Faculty of Medicine*

**Facilitator, Medical Student 4th Year Portfolio Course** [*September, 2013 – May, 2014*]{.cvdate}<br>
*University of Toronto, Faculty of Medicine, Toronto, Canada* -->

# PAPERS REVIEWED

| Journal | Manuscripts Reviewed | Year |
| --- | --- | --- |
| Methodological Innovations | 1 | 2019 |
| Anesthesia Critical Care & Pain Medicine | 1 | 2020 |
| Advances in Medical Education and Practice | 1 | 2020 |
| Journal of Medical Education & Curricular Development | 1 | 2022 |
| British Journal of Anesthesia | 2 | 2022 |
| BMC Health Services Research | 1 | 2022 |
| International Journal of Health Policy and Management** | 1 | 2022 |
| Anesthesia & Analgesia | 1 | 2023 |
| Canadian Journal of Anesthesia | 1 | 2022 |
|  | 1 | 2023 |
|  | 1 | 2024 |
| Journal of Neurosurgical  Anesthesia | 1 | 2024
